### PR TITLE
Fix TOTP seed handling #3785

### LINKED ISSUE #3785: Fix TOTP seed handling inside ZAP wrapper
### Situation
The TOTPGenerator used for webscans needs a seed that is provided as an hex, base32 or base64 encoded string most of the time.
Currently there can be issues based on the chosen charset, if the seed is decoded and saved as string or is encoded afterwards again. Information can be lost or changed during this process.

### Solution
Use the encoded string and decode it only when it is required. Do not transform the datatypes if not necessary.

### PR DESCRIPTION
**Pull request by winzj**
- closes #3785

### CODE REVIEW

File: sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutorTest.java [hunk 1]
```diff
@@ -107,4 +107,26 @@ void valid_script_is_executed_as_expected() throws Exception {
         assertFalse(loginResult.isLoginFailed());
     }
 
+    @Test
+    void valid_script_throws_missing_mandatory_binding_exception_results_in_result_failed() throws Exception {
```
Comment (de-jcup) [inline sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutorTest.java:111]: we should rename the method

File: sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGeneratorTest.java [hunk 2]
```diff
@@ -1,42 +1,42 @@
...
 import com.mercedesbenz.sechub.commons.model.login.TOTPHashAlgorithm;
+import com.mercedesbenz.sechub.commons.model.login.WebLoginTOTPConfiguration;
 
 class TOTPGeneratorTest {
 
     @Test
     void secret_key_being_null_throws_exception() {
         /* execute + test */
-        assertThrows(IllegalArgumentException.class, () -> new TOTPGenerator(null, 6, TOTPHashAlgorithm.HMAC_SHA1, 30));
+        assertThrows(NullPointerException.class, () -> new TOTPGenerator(new WebLoginTOTPConfiguration()));
```
Comment (de-jcup) [inline sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGeneratorTest.java:27]: Please check the content of the NPE here. So it is clear it is not another (unwanted) NPE but the thing we assert...

or we use the UserInfoScriptException here .... and we could here then check the content of the message

File: sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGeneratorTest.java [hunk 3]
```diff
@@ -45,15 +45,34 @@ void generate_the_excpected_otp_with_default_config() throws DecoderException {
         assertEquals(expectedToken, generatedToken);
     }
 
+    @Test
+    void type_conversions_can_produce_errors() {
```
Comment (de-jcup) [inline sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGeneratorTest.java:49]: Is this a test which we need here right now?

File: sechub-wrapper-owasp-zap/src/test/resources/login-script-examples/test-script-custom-exception.groovy [hunk 4]
```diff
@@ -0,0 +1,32 @@
+// SPDX-License-Identifier: MIT
```
Comment (de-jcup) [inline sechub-wrapper-owasp-zap/src/test/resources/login-script-examples/test-script-custom-exception.groovy:1]: I would suggest to just throw here the custom exception and do nothing else.

**Review by de-jcup — CHANGES_REQUESTED** [review]
Good work, but I have found some parts which should be changed.

**Review by de-jcup — APPROVED** [review]
Looks very good - let's merge it :rocket:
