### PR TITLE
Added deployment fixes

### LINKED ISSUE #3883: Web-Ui deployment fixes
## Situation
ENV in web-ui deployment are not red correctly.
Local setup is not described sufficiently

## Wanted
ENV should work properly
Local docker setup should be described sufficient

## Solution
Fix ENVs default and config
Describe local set up in README.md

### PR DESCRIPTION
**Pull request by lorriborri**
- closes #3883

### CODE REVIEW

File: sechub-web-ui/src/components/UserDetailInformation.vue [hunk 1]
```diff
@@ -87,7 +87,7 @@
         </template>
         <v-container>
           <v-list-item-title>{{ $t('USER_SUPPORT_EMAIL') }}</v-list-item-title>
-          <v-list-item-subtitle><a href="mailto:dw_415_sechub-foss@mercedes-benz.com">dw_415_sechub-foss@mercedes-benz.com</a></v-list-item-subtitle>
+          <v-list-item-subtitle><a href="mailto:support@example.sechub.org">support@example.sechub.org</a></v-list-item-subtitle>
```
Comment (sven-dmlr) [inline sechub-web-ui/src/components/UserDetailInformation.vue:90]:
```suggestion
          <v-list-item-subtitle><a href="mailto:example@example.org">example@example.org</a></v-list-item-subtitle>
```

File: sechub-web-ui-solution/README.adoc [hunk 2]
```diff
@@ -6,12 +6,49 @@ The files to create the Web UI container image.
 
 The Web UI is a Vue.js SPA build with nuxt.js.
 
-=== Starting the Web UI on localhost as docker container
+=== Local Web-UI Frontend and SecHub Server SetUp
 
-Following command will run the Web UI on localhost as docker container, with nginx as reverse proxy.
-Attention: currently only self-signed certificates are used.
+1. Please adjust the docker/nginx/nginx.conf file to your needs. +
```
Comment (sven-dmlr) [inline sechub-web-ui-solution/README.adoc:11]: It's a bit uncool to advise people to change a file which is in the repository.
We should think about how this can be done different.

**Review by sven-dmlr — CHANGES_REQUESTED** [review]
Good job! :+1: 
Please check my comments.

File: sechub-web-ui-solution/README.adoc (hunk 2 above)
Comment (lorriborri) [reply sechub-web-ui-solution/README.adoc:11]: https://github.com/mercedes-benz/sechub/issues/3887

**Review by sven-dmlr — APPROVED** [review]
:+1:
