### PR TITLE
pds owasp zap use user messages

### LINKED ISSUE #1823: PDS OWASP ZAP use user messages to send back information about the scan
### Situation
PDS OWASP ZAP does not use user messages to send back information about the scan or the current state of the scan. This results in misleading error messages and the user does not know what happened during the scan. Providing additional messages users will get some information on what happens or happened during the scan.

### Solution
Use user messages to inform users about what happens or what might went wrong during the scan execution.

#### Examples
- send dedicated errors why a scan failed e.g. target not reachable, or configuration invalid
- send additional information on the scan

#### Additional ideas
- send back all scanned URLs collected by crawling mechanisms

### LINKED ISSUE #1829: Inform the user about the scanned urls during DAST scan
### Situation
Currently the user does not really know which parts of the web application where detected an scanned.

### Wanted
Give the user more information on the detected and scanned URLs.

### Possible Solution
Send the scanned URLs back to user using PDS user messages.

### PR DESCRIPTION
**Pull request by winzj**
- closes #1823 
- closes #1829

### CODE REVIEW

File: sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+     */
+    public void writeProductError(ZapWrapperRuntimeException zapWrapperRuntimeException) throws IOException {
+        ZapWrapperExitCode exitCode = zapWrapperRuntimeException.getExitCode();
+        if (exitCode == null) {
+            return;
+        }
+
+        switch (exitCode) {
+        case TARGET_URL_NOT_REACHABLE:
+            productMessageSupport.writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "Target url specified inside sechub config json was not reachable."));
```
Comment (Jeeppler) [inline sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java:40]:
```suggestion
            productMessageSupport.writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "Target URL not reachable. Please check if the target URL, specified inside SecHub configuration, is reachable."));
```

File: sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+            break;
+        case API_DEFINITION_CONFIG_INVALID:
+            productMessageSupport.writeMessage(
+                    new SecHubMessage(SecHubMessageType.ERROR, "Please use a single file for API definitions inside the filesystem->files part."));
```
Comment (Jeeppler) [inline sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java:44]:
```suggestion
                    new SecHubMessage(SecHubMessageType.ERROR, "Only a single API file can be provided. Please use a single file for the API definition inside the filesystem->files section of the SecHub configuration."));
```

File: sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+            break;
+        case TARGET_URL_INVALID:
+            productMessageSupport
+                    .writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "Target url specified inside sechub config json was not a valid URL."));
```
Comment (Jeeppler) [inline sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java:48]:
```suggestion
                    .writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "Target URL invalid. The target URL, specified inside SecHub configuration, is not a valid URL."));
```

File: sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+            break;
+        case PRODUCT_EXECUTION_ERROR:
+            productMessageSupport.writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "The DAST scanner OWASP ZAP ended because of a product error."));
```
Comment (Jeeppler) [inline sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java:51]:
```suggestion
            productMessageSupport.writeMessage(new SecHubMessage(SecHubMessageType.ERROR, "Product error. The DAST scanner OWASP ZAP ended with a product error."));
```

**Review by Jeeppler — APPROVED** [review]
The error messages for the user could be clearer see comments. Otherwise, you can merge it.
